### PR TITLE
Issue #254: Fix PHPdoc issues.

### LINKED ISSUE #254: Fix PHP doc issues
```
admin/tool/excimer/lib.php
    Line 47: Function tool_excimer_performance_checks is not documented
--
admin/tool/excimer/tests/tool_excimer_profile_test.php
    Line 71: Function tool_excimer_profile_test::quick_save is not documented
--
admin/tool/excimer/tests/tool_excimer_script_metadata_test.php
    Line 51: Phpdocs for function tool_excimer_script_metadata_test::test_get_groupby_value has incomplete parameters list
--
admin/tool/excimer/tests/excimer_testcase.php
    Line 39: Phpdocs for function excimer_testcase::get_log_entry_stub has incomplete parameters list
    Line 84: Phpdocs for function excimer_testcase::get_log_stub has incomplete parameters list
    Line 129: Phpdocs for function excimer_testcase::get_profiler_stub has incomplete parameters list
    Line 24: Package tool_eximer is not valid
--
admin/tool/excimer/tests/tool_excimer_profile_helper_test.php
    Line 73: Function tool_excimer_profile_helper_test::quick_save is not documented
    Line 251: There is no description in phpdocs for function mock_profile_insertion_with_duration
--
admin/tool/excimer/db/upgrade.php
    Line 26: Function xmldb_tool_excimer_upgrade is not documented
--
admin/tool/excimer/version.php
    Line 17: No one-line description found in phpdocs for file
--
admin/tool/excimer/classes/profile.php
    Line 83: Function profile::get_flamedatad3 is not documented
    Line 108: Function profile::get_memoryusagedatad3 is not documented
    Line 126: Function profile::add_env is not documented
    Line 31: Constant profile::TABLE is not documented
    Line 58: Constant profile::REASON_STR_MAP is not documented
    Line 65: Constant profile::SCRIPTTYPE_AJAX is not documented
    Line 66: Constant profile::SCRIPTTYPE_CLI is not documented
    Line 67: Constant profile::SCRIPTTYPE_WEB is not documented
    Line 68: Constant profile::SCRIPTTYPE_WS is not documented
    Line 69: Constant profile::SCRIPTTYPE_TASK is not documented
    Line 112: Phpdocs for function profile::get_uncompressed_json has incomplete parameters list
admin/tool/excimer/classes/grouped_profile_table.php
    Line 38: Function grouped_profile_table::put_sql is not documented
    Line 50: Function grouped_profile_table::get_columns is not documented
    Line 58: Function grouped_profile_table::col_group is not documented
    Line 71: Function grouped_profile_table::col_maxcreated is not documented
    Line 74: Function grouped_profile_table::col_mincreated is not documented
    Line 77: Function grouped_profile_table::col_maxduration is not documented
    Line 80: Function grouped_profile_table::col_minduration is not documented
    Line 84: Function grouped_profile_table::col_actions is not documented
    Line 29: Constant grouped_profile_table::COLUMNS is not documented
admin/tool/excimer/classes/profile_table.php
    Line 43: Variable profile_table::$filters is not documented
    Line 45: Variable profile_table::$scripttypes is not documented
    Line 29: Constant profile_table::COLUMNS is not documented
    Line 39: Constant profile_table::NOSORT_COLUMNS is not documented
admin/tool/excimer/classes/sample_set.php
    Line 28: Variable sample_set::$name is not documented
    Line 29: Variable sample_set::$starttime is not documented
    Line 36: Variable sample_set::$maxstackdepth is not documented
    Line 50: Phpdocs for function sample_set::__construct has incomplete parameters list
admin/tool/excimer/classes/script_metadata.php
    Line 64: Constant script_metadata::SAMPLING_PERIOD_MIN is not documented
    Line 65: Constant script_metadata::SAMPLING_PERIOD_MAX is not documented
    Line 66: Constant script_metadata::SAMPLING_PERIOD_DEFAULT is not documented
    Line 68: Constant script_metadata::TIMER_INTERVAL_MIN is not documented
    Line 69: Constant script_metadata::TIMER_INTERVAL_DEFAULT is not documented
    Line 71: Constant script_metadata::STACK_DEPTH_LIMIT is not documented
    Line 73: Constant script_metadata::SAMPLE_LIMIT_DEFAULT is not documented
    Line 242: Constant script_metadata::PLUGINFILE_SCRIPTS is not documented
    Line 248: There is no description in phpdocs for function get_groupby_value
admin/tool/excimer/classes/flamed3_node.php
    Line 33: Function flamed3_node::__construct is not documented
    Line 29: Variable flamed3_node::$name is not documented
    Line 30: Variable flamed3_node::$value is not documented
    Line 31: Variable flamed3_node::$children is not documented
admin/tool/excimer/classes/output/tabs.php
    Line 28: Variable tabs::$activeurl is not documented
--
admin/tool/excimer/classes/helper.php
    Line 163: Function helper::full_request is not documented
    Line 144: Phpdocs for function helper::status_display has incomplete parameters list
--
admin/tool/excimer/classes/task/expire_logs.php
    Line 30: Class expire_logs is not documented
    Line 32: Function expire_logs::get_name is not documented
    Line 36: Function expire_logs::execute is not documented
admin/tool/excimer/classes/task/purge_fastest.php
    Line 30: Class purge_fastest is not documented
    Line 32: Function purge_fastest::get_name is not documented
    Line 36: Function purge_fastest::execute is not documented
admin/tool/excimer/classes/web_processor.php
    Line 36: Variable web_processor::$memoryusagesampleset is not documented
admin/tool/excimer/classes/processor.php
    Line 31: Package is not specified for function init. It is also not specified in file-level phpdocs
    Line 38: Package is not specified for function get_min_duration. It is also not specified in file-level phpdocs
admin/tool/excimer/classes/privacy/provider.php
    Line 39: Function provider::get_metadata is not documented
--
admin/tool/excimer/classes/recent_profile_table.php
    Line 29: Constant recent_profile_table::COLUMNS is not documented
admin/tool/excimer/classes/profile_helper.php
    Line 49: Phpdocs for function profile_helper::get_min_duration_for_group_and_reason has incomplete parameters list
admin/tool/excimer/classes/manager.php
    Line 34: Variable manager::$processor is not documented
    Line 35: Variable manager::$profiler is not documented
    Line 36: Variable manager::$timer is not documented
    Line 37: Variable manager::$starttime is not documented
    Line 29: Constant manager::FLAME_ME_PARAM_NAME is not documented
    Line 30: Constant manager::FLAME_ON_PARAM_NAME is not documented
    Line 31: Constant manager::FLAME_OFF_PARAM_NAME is not documented
    Line 32: Constant manager::NO_FLAME_PARAM_NAME is not documented
    Line 207: Phpdocs for function manager::is_considered_slow has incomplete parameters list
admin/tool/excimer/classes/profile_table_page.php
    Line 21: Class profile_table_page is not documented
    Line 21: Package is not specified for class profile_table_page. It is also not specified in file-level phpdocs
admin/tool/excimer/cli/simtask.php
    Line 34: Constant NUM_REPEAT is not documented
    Line 17: No one-line description found in phpdocs for file
```

### PR DESCRIPTION
**Pull request by jaypha**
Resolves #254

### CODE REVIEW

File: classes/grouped_profile_table.php [hunk 1]
```diff
@@ -68,19 +83,52 @@ public function col_group(\stdClass $record): string {
...
 
+    /**
+     * Max created column.
+     *
+     * @param \stdClass $record
+     * @return string
+     */
     public function col_maxcreated(\stdClass $record): string {
-        return userdate($record->mincreated, get_string('strftime_datetime', 'tool_excimer'));
+        return userdate($record->maxcreated, get_string('strftime_datetime', 'tool_excimer'));
```
Comment (keevan) [inline classes/grouped_profile_table.php:93]: Nice spot :)

**Review by keevan — APPROVED** [review]
Everything looks good. Thanks for making the changes Jason.
